-- CreateEnum
CREATE TYPE "RegistrationStep" AS ENUM ('CREATE_ACCOUNT', 'VERIFY', 'CREATE_BIODATA', 'PROVIDE_MEDICAL_CERTIFICATIONS', 'COMPLIANCE_AND_SECURITY_CHECK', 'PROFILE_COMPLETE');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "isProfileComplete" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "registrationStep" "RegistrationStep" NOT NULL DEFAULT 'CREATE_ACCOUNT';
