name: Auto Deployment with Prisma Migrations

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js 14
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
    
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # - name: 📂 Copy Files to Server via SSH
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     source: "."  
      #     target: "/var/www/api/mydocngApi"  # Change this to your project directory

      - name: 🔄 SSH into Server and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/api/mydocngApi
            git pull origin master  # Fetch latest changes
            yarn install           # Install dependencies
            npx prisma migrate deploy  # ✅ Apply Prisma migrations
            npx prisma generate         # ✅ Generate Prisma Client
            yarn run build         # Build project (if needed)
            pm2 restart mydocng-api # Restart app using PM2
